#!/data/data/com.termux/files/usr/bin/bash

[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.termux"

/system/bin/app_process -Djava.class.path="/data/data/com.termux/files/home/rish_shizuku.dex" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "${@}"
