#!/data/data/com.termux/files/usr/bin/bash

read ip port < <(./adbw_port _adb._tcp.local. \
  | sed -n -e 's/.*ipv4: \([0-9.]*\), port: \([0-9]*\).*/\1 \2/p')
device="${ip}:${port}"
echo "DEBUG device='$device'"

if [[ -z "$ip" || -z "$port" ]]; then
  echo "ERROR: Không tìm thấy IP hoặc port! Output:"; ./adbw_port _adb._tcp.local.
  exit 1
fi

adb -s "$device" connect "$device" >/dev/null
echo -n "Kết nối ADB… "
if ! adb -s "$device" shell echo connected >/dev/null 2>&1; then
  echo "Thất bại"; exit 1
fi
echo "Thành công!"

# Xác định path .apk và libshizuku.so
sh_path=$(adb -s "$device" shell pm path --user 0 moe.shizuku.privileged.api \
  | sed 's/^package://')
lib_path=$(adb -s "$device" shell "echo \$(dirname \"$sh_path\")/lib/*/libshizuku.so")

echo "Khởi Shizuku từ $lib_path"
adb -s "$device" shell "$lib_path"

# Tắt wireless debugging
#adb -s "$device" shell settings put global adb_wifi_enabled 0
#echo "Đã tắt wireless debugging ✅"

